#Makefile for "first in class" CS2600

CC = gcc

number: src\\numbersGame.c
	$(CC) -o bin\\numbersGame src\\numbersGame.c

bill: src\\restaurantBill.c
	$(CC) -o bin\\restaurantBill src\\numbersGame.c
